version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: |
          cd wordpress-k8s-rds/cnab
          docker build -t test-todo:$CIRCLE_BRANCH .
